dirs:
  data_dir: data
  train_dir: train
  test_dir: test
  image_dir: images
  mask_dir: masks
  model_dir: models
  output_dir: output/hybrid_experiment
  pred_mask_dir: predicted_masks
  pred_plot_dir: prediction_plots
  log_dir: logs
vars:
  train_log_name: hybrid_train.log
  test_log_name: hybrid_test.log
  log_level: 'DEBUG'
  file_type: '.tif'
  patch_size: 512
  discard_rate: 0.95
  batch_size: 8  # Moderate batch size for hybrid model
  model_arch: 'HybridCNNTransformer'  # Hybrid CNN-Transformer model
  model_name: trained_landcover_hybrid_cnn-transformer_epochs20_patch512_batch8.pth
  encoder: 'cnn-transformer'  # Hybrid encoder
  encoder_weights: 'imagenet'
  activation: 'softmax2d'
  optimizer_choice: 'AdamW'
  init_lr: 0.0001
  reduce_lr_by_factor: 0.5
  patience_epochs_before_reducing_lr: 5
  lr_reduce_threshold: 0.0001
  minimum_lr: 0
  epochs: 20
  device: 'cpu'
  all_classes: ['background', 'building', 'woodland', 'water', 'road']
  train_classes: ['background', 'building', 'woodland', 'water']
  test_classes: ['background', 'building', 'water']
